#!/bin/bash

set -eo pipefail

rm -rf ./bin
mkdir -p ./bin
IMAGE="fluent-bit-kinesis"

docker build -t $IMAGE --build-arg version=$(cat VERSION) .
id=$(docker create $IMAGE)
docker cp $id:/app/bin/. ./bin/
docker rm $id

sha256sum ./bin/*
